name: Test Examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  execute-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install
          npm install -g ts-node

      - name: Run Examples
        run: |
          examples=$(find ./examples -name "*.ts")
          for example in $examples; do
            ts-node $example > /dev/null
            exit_code=$?
            if [ $exit_code -ne 0 ]; then
              echo "Error executing $example"
              exit 1
            fi
          done
